spring.application.name=RouteShare
spring.datasource.url=jdbc:mysql://localhost:3306/routesharedb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google Maps Integration
google.maps.api-key=AIzaSyBV9e0UnadjfgSehlCAlLq9umiciBEBGmA

