package com.routeshare.repository;

import com.routeshare.model.Notification;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * NotificationRepository abstracts persistence for Notification entities.
 *
 * Demonstrates:
 * - Repository Pattern: Derived query methods generated by Spring Data JPA.
 */
@Repository
public interface NotificationRepository extends JpaRepository<Notification, Long> {

    List<Notification> findByRecipientIdOrderByCreatedAtDesc(Long recipientId);

    long countByRecipientIdAndReadIsFalse(Long recipientId);

    List<Notification> findByRecipientIdAndReadIsFalse(Long recipientId);
}
